### ISSUE TITLE
 ENOENT, no such file or directory '/tmp/archive-docker-build-1423077557112.tar

### ISSUE THREAD

**Issue by jasperla** [Strider-CD/strider-docker-build#15]
Hi,

I'm running into some issues trying to build a Docker image:

```
strider stdout | 2015-02-04T19:19:18.659Z - info: Job 54d270b561247659009b8daa  domain error caught ENOENT, no such file or directory '/tmp/archive-docker-build-1423077557112.tar' Error: ENOENT, no such file or directory '/tmp/archive-docker-build-1423077557112.tar'
    at Object.fs.openSync (fs.js:432:18)
    at Object.fs.readFileSync (fs.js:286:15)
    at Modem.dial (/opt/strider/src/node_modules/strider-docker-build/node_modules/dockerode/node_modules/docker-modem/lib/modem.js:117:17)
    at Docker.buildImage (/opt/strider/src/node_modules/strider-docker-build/node_modules/dockerode/lib/docker.js:146:14)
    at Object.prepare (/opt/strider/src/node_modules/strider-docker-build/lib/build.js:15:12)
    at Object.runPlugin (/opt/strider/src/node_modules/strider-simple-runner/node_modules/strider-runner-core/lib/utils.js:26:25)
    at /opt/strider/src/node_modules/strider-simple-runner/node_modules/strider-runner-core/lib/job.js:293:15
    at /opt/strider/src/node_modules/strider-simple-runner/node_modules/strider-runner-core/node_modules/async/lib/async.js:551:21
    at /opt/strider/src/node_modules/strider-simple-runner/node_modules/strider-runner-core/node_modules/async/lib/async.js:227:13
    at iterate (/opt/strider/src/node_modules/strider-simple-runner/node_modules/strider-runner-core/node_modules/async/lib/async.js:134:13)
    at /opt/strider/src/node_modules/strider-simple-runner/node_modules/strider-runner-core/node_modules/async/lib/async.js:145:25
    at /opt/strider/src/node_modules/strider-simple-runner/node_modules/strider-runner-core/node_modules/async/lib/async.js:229:17
    at /opt/strider/src/node_modules/strider-simple-runner/node_modules/strider-runner-core/node_modules/async/lib/async.js:556:34
    at /opt/strider/src/node_modules/strider-git/worker.js:119:5
    at ChildProcess.<anonymous> (/opt/strider/src/node_modules/strider-simple-runner/node_modules/strider-runner-core/lib/job.js:203:9)
    at ChildProcess.EventEmitter.emit (events.js:98:17)
    at Process.ChildProcess._handle.onexit (child_process.js:797:12)
strider stderr | 2015-02-04T19:19:18.659Z - error: Job 54d270b561247659009b8daa  ENOENT, no such file or directory '/tmp/archive-docker-build-1423077557112.tar' Error: ENOENT, no such file or directory '/tmp/archive-docker-build-1423077557112.tar'
    at Object.fs.openSync (fs.js:432:18)
    at Object.fs.readFileSync (fs.js:286:15)
    at Modem.dial (/opt/strider/src/node_modules/strider-docker-build/node_modules/dockerode/node_modules/docker-modem/lib/modem.js:117:17)
    at Docker.buildImage (/opt/strider/src/node_modules/strider-docker-build/node_modules/dockerode/lib/docker.js:146:14)
    at Object.prepare (/opt/strider/src/node_modules/strider-docker-build/lib/build.js:15:12)
    at Object.runPlugin (/opt/strider/src/node_modules/strider-simple-runner/node_modules/strider-runner-core/lib/utils.js:26:25)
    at /opt/strider/src/node_modules/strider-simple-runner/node_modules/strider-runner-core/lib/job.js:293:15
    at /opt/strider/src/node_modules/strider-simple-runner/node_modules/strider-runner-core/node_modules/async/lib/async.js:551:21
    at /opt/strider/src/node_modules/strider-simple-runner/node_modules/strider-runner-core/node_modules/async/lib/async.js:227:13
    at iterate (/opt/strider/src/node_modules/strider-simple-runner/node_modules/strider-runner-core/node_modules/async/lib/async.js:134:13)
    at /opt/strider/src/node_modules/strider-simple-runner/node_modules/strider-runner-core/node_modules/async/lib/async.js:145:25
    at /opt/strider/src/node_modules/strider-simple-runner/node_modules/strider-runner-core/node_modules/async/lib/async.js:229:17
    at /opt/strider/src/node_modules/strider-simple-runner/node_modules/strider-runner-core/node_modules/async/lib/async.js:556:34
    at /opt/strider/src/node_modules/strider-git/worker.js:119:5
    at ChildProcess.<anonymous> (/opt/strider/src/node_modules/strider-simple-runner/node_modules/strider-runner-core/lib/job.js:203:9)
    at ChildProcess.EventEmitter.emit (events.js:98:17)
    at Process.ChildProcess._handle.onexit (child_process.js:797:12)
strider stdout | 2015-02-04T19:19:18.662Z - info: [runner:simple-runner] Job done with error. Project: jasperla/nginx Job ID: 54d270b561247659009b8daa
```

This seems happens when I change the phase for Docker Build to 'prepare'

**Comment by davemackintosh** [comment]
there is a bug in this where if you select the prepare phase it doesn't run the default (where it creates the tar) this is due to a limitation in the Strider core that doesn't support multiple callbacks for each phase of the build.

The fix is to set it to environment or test

**Comment by knownasilya** [comment]
@davemackintosh could you remove the prepare phase from the list?

**Comment by davemackintosh** [comment]
Sure can, I wish I had more time to add this feature to Strider core.
