### ISSUE TITLE
Error while pushing image

### ISSUE THREAD

**Issue by tyagiamreesh** [Strider-CD/strider-docker-build#21]
**Error:** (HTTP code 400) unexpected - Bad parameters and missing X-Registry-Auth: EOF

**Error log:**

`Successfully built aa74d2b6456a
Successfully tagged latest:latest
An unexpected error occurred while executing this job. Please report at https://github.com/Strider-CD/strider/issues

(HTTP code 400) unexpected - Bad parameters and missing X-Registry-Auth: EOF 

Error: (HTTP code 400) unexpected - Bad parameters and missing X-Registry-Auth: EOF 
    at /home/atyagi/striderCD/strider/node_modules/strider-docker-build/node_modules/docker-modem/lib/modem.js:254:17
    at IncomingMessage.<anonymous> (/home/atyagi/striderCD/strider/node_modules/strider-docker-build/node_modules/docker-modem/lib/modem.js:281:9)
    at IncomingMessage.emit (events.js:187:15)
    at IncomingMessage.EventEmitter.emit (domain.js:460:23)
    at endReadableNT (_stream_readable.js:1092:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)`

**Comment by saas-plat** [comment]
see https://github.com/Strider-CD/strider-docker-build/pull/22
